version: "3.9"

services:
  dr-mirotalk:
    build: .
    ports:
      - "3015:3015"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3015
      DATABASE_URL: file:/data/dev.db
    volumes:
      - dr_mirotalk_data:/data

volumes:
  dr_mirotalk_data:
